build/X86_MESI_Two_Level/gem5.opt -re  --outdir=../results/chkpt_march20/GAPBS/bc_22    configs-npb-gapbs/gapbs_checkpoint.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-gapbs  timing 8 MESI_Two_Level  bc    1 22  
build/X86_MESI_Two_Level/gem5.opt -re  --outdir=../results/chkpt_march20/GAPBS/bfs_22   configs-npb-gapbs/gapbs_checkpoint.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-gapbs  timing 8 MESI_Two_Level  bfs   1 22  
build/X86_MESI_Two_Level/gem5.opt -re  --outdir=../results/chkpt_march20/GAPBS/cc_22    configs-npb-gapbs/gapbs_checkpoint.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-gapbs  timing 8 MESI_Two_Level  cc    1 22  
build/X86_MESI_Two_Level/gem5.opt -re  --outdir=../results/chkpt_march20/GAPBS/pr_22    configs-npb-gapbs/gapbs_checkpoint.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-gapbs  timing 8 MESI_Two_Level  pr    1 22  
build/X86_MESI_Two_Level/gem5.opt -re  --outdir=../results/chkpt_march20/GAPBS/tc_22    configs-npb-gapbs/gapbs_checkpoint.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-gapbs  timing 8 MESI_Two_Level  tc    1 22  
build/X86_MESI_Two_Level/gem5.opt -re  --outdir=../results/chkpt_march20/GAPBS/sssp_22  configs-npb-gapbs/gapbs_checkpoint.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-gapbs  timing 8 MESI_Two_Level  sssp  1 22  


build/X86_MESI_Two_Level/gem5.opt -re  --outdir=../results/rstr_march20/GAPBS/bc_22    configs-npb-gapbs/gapbs_restore.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-gapbs  timing 8 MESI_Two_Level  bc    1 22  /home/babaie/projects/ispass2023/runs/results/cptTest/GAPBS_Cas/cpt_100ms_22/bc_22/cpt
build/X86_MESI_Two_Level/gem5.opt -re  --outdir=../results/rstr_march20/GAPBS/bfs_22   configs-npb-gapbs/gapbs_restore.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-gapbs  timing 8 MESI_Two_Level  bfs   1 22  /home/babaie/projects/ispass2023/runs/results/cptTest/GAPBS_Cas/cpt_100ms_22/bfs_22/cpt
build/X86_MESI_Two_Level/gem5.opt -re  --outdir=../results/rstr_march20/GAPBS/cc_22    configs-npb-gapbs/gapbs_restore.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-gapbs  timing 8 MESI_Two_Level  cc    1 22  /home/babaie/projects/ispass2023/runs/results/cptTest/GAPBS_Cas/cpt_100ms_22/cc_22/cpt
build/X86_MESI_Two_Level/gem5.opt -re  --outdir=../results/rstr_march20/GAPBS/pr_22    configs-npb-gapbs/gapbs_restore.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-gapbs  timing 8 MESI_Two_Level  pr    1 22  /home/babaie/projects/ispass2023/runs/results/cptTest/GAPBS_Cas/cpt_100ms_22/pr_22/cpt
build/X86_MESI_Two_Level/gem5.opt -re  --outdir=../results/rstr_march20/GAPBS/tc_22    configs-npb-gapbs/gapbs_restore.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-gapbs  timing 8 MESI_Two_Level  tc    1 22  /home/babaie/projects/ispass2023/runs/results/cptTest/GAPBS_Cas/cpt_100ms_22/tc_22/cpt
build/X86_MESI_Two_Level/gem5.opt -re  --outdir=../results/rstr_march20/GAPBS/sssp_22  configs-npb-gapbs/gapbs_restore.py /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-linux-kernel-4.19.83 /home/babaie/projects/ispass2023/runs/hbmCtrlrTest/dramCacheController/fullSystemDisksKernel/x86-gapbs  timing 8 MESI_Two_Level  sssp  1 22  /home/babaie/projects/ispass2023/runs/results/cptTest/GAPBS_Cas/cpt_100ms_22/sssp_22/cpt
