# build/X86_MESI_Two_Level/gem5.opt -re --outdir=cpt-resub/8ch/chkpt-atomic/gapbs/25/bc    configs-npb-gapbs-chkpt-restore/checkpoint_both.py bc    25 &
# build/X86_MESI_Two_Level/gem5.opt -re --outdir=cpt-resub/8ch/chkpt-atomic/gapbs/25/bfs   configs-npb-gapbs-chkpt-restore/checkpoint_both.py bfs   25 &
# build/X86_MESI_Two_Level/gem5.opt -re --outdir=cpt-resub/8ch/chkpt-atomic/gapbs/25/cc    configs-npb-gapbs-chkpt-restore/checkpoint_both.py cc    25 &
# build/X86_MESI_Two_Level/gem5.opt -re --outdir=cpt-resub/8ch/chkpt-atomic/gapbs/25/pr    configs-npb-gapbs-chkpt-restore/checkpoint_both.py pr    25 &
# build/X86_MESI_Two_Level/gem5.opt -re --outdir=cpt-resub/8ch/chkpt-atomic/gapbs/25/sssp  configs-npb-gapbs-chkpt-restore/checkpoint_both.py sssp  25 &
# build/X86_MESI_Two_Level/gem5.opt -re --outdir=cpt-resub/8ch/chkpt-atomic/gapbs/25/tc    configs-npb-gapbs-chkpt-restore/checkpoint_both.py tc    25 &
# build/X86_MESI_Two_Level/gem5.opt -re --outdir=cpt-resub/8ch/chkpt-atomic/npb/D/bt       configs-npb-gapbs-chkpt-restore/checkpoint_both.py bt     D  &
# build/X86_MESI_Two_Level/gem5.opt -re --outdir=cpt-resub/8ch/chkpt-atomic/npb/D/cg       configs-npb-gapbs-chkpt-restore/checkpoint_both.py cg     D  &
# build/X86_MESI_Two_Level/gem5.opt -re --outdir=cpt-resub/8ch/chkpt-atomic/npb/D/ft       configs-npb-gapbs-chkpt-restore/checkpoint_both.py ft     D  &
# build/X86_MESI_Two_Level/gem5.opt -re --outdir=cpt-resub/8ch/chkpt-atomic/npb/D/is       configs-npb-gapbs-chkpt-restore/checkpoint_both.py is     D  &
# build/X86_MESI_Two_Level/gem5.opt -re --outdir=cpt-resub/8ch/chkpt-atomic/npb/D/lu       configs-npb-gapbs-chkpt-restore/checkpoint_both.py lu     D  &
# build/X86_MESI_Two_Level/gem5.opt -re --outdir=cpt-resub/8ch/chkpt-atomic/npb/D/mg       configs-npb-gapbs-chkpt-restore/checkpoint_both.py mg     D  &
# build/X86_MESI_Two_Level/gem5.opt -re --outdir=cpt-resub/8ch/chkpt-atomic/npb/D/sp       configs-npb-gapbs-chkpt-restore/checkpoint_both.py sp     D  &
# build/X86_MESI_Two_Level/gem5.opt -re --outdir=cpt-resub/8ch/chkpt-atomic/npb/D/ua       configs-npb-gapbs-chkpt-restore/checkpoint_both.py ua     D  &


# build/X86_MESI_Two_Level/gem5.opt -re --outdir=cpt-resub/test/gapbs/22/bc    configs-npb-gapbs-chkpt-restore/checkpoint_both.py bc    22 &
# build/X86_MESI_Two_Level/gem5.opt -re --outdir=cpt-resub/test/gapbs/22/bfs   configs-npb-gapbs-chkpt-restore/checkpoint_both.py bfs   22 &
# build/X86_MESI_Two_Level/gem5.opt -re --outdir=cpt-resub/test/gapbs/22/cc    configs-npb-gapbs-chkpt-restore/checkpoint_both.py cc    22 &
# build/X86_MESI_Two_Level/gem5.opt -re --outdir=cpt-resub/test/gapbs/22/pr    configs-npb-gapbs-chkpt-restore/checkpoint_both.py pr    22 &
# build/X86_MESI_Two_Level/gem5.opt -re --outdir=cpt-resub/test/gapbs/22/sssp  configs-npb-gapbs-chkpt-restore/checkpoint_both.py sssp  22 &
# build/X86_MESI_Two_Level/gem5.opt -re --outdir=cpt-resub/test/gapbs/22/tc    configs-npb-gapbs-chkpt-restore/checkpoint_both.py tc    22 &
# build/X86_MESI_Two_Level/gem5.opt -re --outdir=cpt-resub/test/npb/C/bt       configs-npb-gapbs-chkpt-restore/checkpoint_both.py bt    C  &
# build/X86_MESI_Two_Level/gem5.opt -re --outdir=cpt-resub/test/npb/C/cg       configs-npb-gapbs-chkpt-restore/checkpoint_both.py cg    C  &
# build/X86_MESI_Two_Level/gem5.opt -re --outdir=cpt-resub/test/npb/C/ft       configs-npb-gapbs-chkpt-restore/checkpoint_both.py ft    C  &
# build/X86_MESI_Two_Level/gem5.opt -re --outdir=cpt-resub/test/npb/C/is       configs-npb-gapbs-chkpt-restore/checkpoint_both.py is    C  &
# build/X86_MESI_Two_Level/gem5.opt -re --outdir=cpt-resub/test/npb/C/lu       configs-npb-gapbs-chkpt-restore/checkpoint_both.py lu    C  &
build/X86_MESI_Two_Level/gem5.opt -re --outdir=cpt-resub/test/npb/C/mg       configs-npb-gapbs-chkpt-restore/checkpoint_both.py mg    C  &
# build/X86_MESI_Two_Level/gem5.opt -re --outdir=cpt-resub/test/npb/C/sp       configs-npb-gapbs-chkpt-restore/checkpoint_both.py sp    C  &
# build/X86_MESI_Two_Level/gem5.opt -re --outdir=cpt-resub/test/npb/C/ua       configs-npb-gapbs-chkpt-restore/checkpoint_both.py ua    C  &
