Import('main')

# Include?
main.Prepend(CPPPATH=Dir('./'))
main.Prepend(CPPPATH=Dir('/usr/share/verilator/include'))
main.Prepend(CPPPATH=Dir('/usr/share/verilator/include/vltstd'))

sodor = main.Clone()

#main.Append(LIBS=['VTop__ALL'])
#main.Prepend(LIBPATH=[Dir('.')])
