Import('*')

if not env['CONF']['USE_NULL_ISA']:
    SimObject('LoopPoint.py', sim_objects=['LoopPoint'])
    Source('looppoint.cc')

    SimObject('LoopPointManager.py', sim_objects=['LoopPointManager'])
    Source('looppointmanager.cc')
