# Copyright (c) 2021-25 The Regents of the University of California
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met: redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer;
# redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution;
# neither the name of the copyright holders nor the names of its
# contributors may be used to endorse or promote products derived from
# this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Import('*')

# SimObject('DualPort.py', sim_objects=['DualPort'])
# SimObject('SimpleBlockingPort.py', sim_objects=['SimpleBlockingPort'])
# SimObject('SimplePort.py', sim_objects=['SimplePort'])
SimObject('FlatTables.py', sim_objects=['FlatTables'])
# SimObject('Mondrian.py', sim_objects=['Mondrian'])
# SimObject('MyUIODevice.py', sim_objects=['MyUIODevice'])

# Source('dual_port.cc')
# Source('simple_blocking_port.cc')
# Source('simple_port.cc')
Source('flat_tables.cc')
# Source('mondrain.cc')
# Source('my_uio_device.cc')

# SimObject('MyPCIDevice.py', sim_objects=['MyPCIDevice'])
# Source('my_pci_device.cc')


# Here are the debug flags used in the source code.
# DebugFlag('DualPort', "Making sure everything works!")
# DebugFlag('PermissionTable', "Making sure that the permission table works!")
# DebugFlag('PermissionTableEvent', "Making sure that the permission table works!")
# # DebugFlag('SimpleBlockingPort', "The other implementation")
# # DebugFlag('SimplePort', "The simple implementation")
DebugFlag('FlatTablesDebug', "For the latency memory object")
# DebugFlag('MondrianDebug', "For the latency memory object")
# DebugFlag('PermissionPackets', "For custom packets")
DebugFlag('RemoteAddress', "For debugging if packets go to the remote memory")
DebugFlag('PermissionResponses', "For debugging responses only")

# DebugFlag('MyUIODevice', "For the MyUIODevice SimObject")

DebugFlag('PermissionCaching', "For debugging the cache")
DebugFlag('FlatPermissionTables', "Making sure that the permission table works!")