from typing import overload

class EthAddr:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: str) -> None: ...
    @overload
    def __init__(*args, **kwargs) -> Any: ...

class IpAddress:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: int) -> None: ...
    @overload
    def __init__(*args, **kwargs) -> Any: ...

class IpNetmask(IpAddress):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int) -> None: ...
    @overload
    def __init__(*args, **kwargs) -> Any: ...

class IpWithPort(IpAddress):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, arg0: int, arg1: int) -> None: ...
    @overload
    def __init__(*args, **kwargs) -> Any: ...
