def disable(*args, **kwargs) -> Any: ...
def enable(*args, **kwargs) -> Any: ...
def ignore(arg0: str) -> None: ...
def output(arg0: str) -> None: ...

class BaseGen:
    def __init__(self, *args, **kwargs) -> None: ...
