# This workflow runs after a pull-request has been approved by a reviewer.

name: CI Tests

on: [push]


jobs:

  # ensures we have a change-id in every commit, needed for gerrit
  check-for-change-id:
    # runs on github hosted runners
    runs-on: ubuntu-latest
    container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest
    steps:
      - uses: actions/github-script@v6
        env:
          token: "Change-Id"
          pattern: ".*"
        with:
          script: |
            const commits = ${{ toJSON(github.event.commits) }}
            for (const commit of commits) {
              const id = "Change-Id: "
              const message = commit.message;
              if (!message.includes(id)) {
                core.setFailed('One or more of the commits in this pull request is missing a Change-ID, which we require for any changes made to gem5. ' +
                'To automatically insert one, run the following:\n f=`git rev-parse --git-dir`/hooks/commit-msg ; mkdir -p $(dirname $f) ; ' +
                'curl -Lo $f https://gerrit-review.googlesource.com/tools/hooks/commit-msg ; chmod +x $f\n Then amend the commit with git commit --amend --no-edit, and update your pull request.')
              }
            }