# This workflow runs after a pull-request has been approved by a reviewer

name: CI Tests

on:
  pull_request:
    types: [opened, edited, synchronize, ready_for_review]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          for commit in $(git rev-list ${{ github.event.before}}..${{ github.sha}}); do
              git checkout $commit
              git log -1 --pretty=format:"%s" >> msg.txt
              if git interpret-trailers --parse < msg.txt | grep -q "^Change-Id: $" ; then
                exit 0
              fi
              echo "run test"
          done
