Import("*")

SimObject("DataCell.py", sim_objects=["DataCell"])
SimObject("SuperNetwork.py", sim_objects=["SuperNetwork"])
SimObject("Layer.py", sim_objects=["Layer"])

Source("data_cell.cc")
Source("super_network.cc")
Source("layer.cc")
Source("network_scheduler.cc")

DebugFlag("SuperNetwork")
DebugFlag("DataCell")
DebugFlag("NetworkScheduler")
DebugFlag("Layer")
